/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GroupeListingGroupe.java
 *
 * Created on 28-mars-2009, 18:31:26
 */

package View.groupe;

/**
 *
 * @author Cramike
 */
public class GroupeListingGroupe extends javax.swing.JPanel {

    /** Creates new form GroupeListingGroupe */
    public GroupeListingGroupe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("jLabel2");
        add(jLabel2, new java.awt.GridBagConstraints());

        jLabel3.setText("jLabel3");
        add(jLabel3, new java.awt.GridBagConstraints());

        jLabel4.setText("jLabel4");
        add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setText("jLabel5");
        add(jLabel5, new java.awt.GridBagConstraints());

        jLabel6.setText("jLabel6");
        add(jLabel6, new java.awt.GridBagConstraints());

        jLabel7.setText("jLabel7");
        add(jLabel7, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
