/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnexPanel.java
 *
 * Created on 12-avr.-2009, 17:45:18
 */
package View;

import Controller.Controller;
import Data.BDException;
import Data.ConnexBD;
import Data.LoginException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Cramike
 */
public class ConnexPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /** Creates new form ConnexPanel */
    public ConnexPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelConnex = new javax.swing.JLabel();
        labelDBName = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        labelPass = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        actionPanel = new javax.swing.JPanel();
        butQuitter = new javax.swing.JButton();
        butConnect = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        labelConnex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/login.png"))); // NOI18N
        labelConnex.setText("Connexion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        add(labelConnex, gridBagConstraints);

        labelDBName.setText("Nom d'utilisateur :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(labelDBName, gridBagConstraints);

        textUsername.setText("Cramike");
        textUsername.setMinimumSize(new java.awt.Dimension(110, 20));
        textUsername.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        add(textUsername, gridBagConstraints);

        labelPass.setText("Mot de passe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(labelPass, gridBagConstraints);

        password.setText("Osiris");
        password.setMinimumSize(new java.awt.Dimension(110, 20));
        password.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        add(password, gridBagConstraints);

        butQuitter.setText("Quitter");
        butQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butQuitterActionPerformed(evt);
            }
        });
        actionPanel.add(butQuitter);

        butConnect.setText("Se connecter");
        butConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConnectActionPerformed(evt);
            }
        });
        actionPanel.add(butConnect);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(actionPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void butQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butQuitterActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_butQuitterActionPerformed

    private void butConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConnectActionPerformed
        if (!(new String(password.getPassword()).isEmpty()) && !(textUsername.getText()).isEmpty()) {
            try {
                if (Controller.connectUser(textUsername.getText(), new String(password.getPassword()))) {
                    mainFrame.afficherPanel(new BienvenuePanel());
                    mainFrame.getJMenuBar().setVisible(true);
                }
            } catch (BDException ex) {
                JOptionPane.showMessageDialog(null, "<html>La connexion n'a pas pu s'établir, veuillez recommencer<br><br><i>Si le problème persiste, veuillez contacter un adiministrateur</i>", "Erreur", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }

    public JPasswordField getPassword() {
        return password;
    }

    public JTextField getTextDBName() {
        return textUsername;
    }//GEN-LAST:event_butConnectActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton butConnect;
    private javax.swing.JButton butQuitter;
    private javax.swing.JLabel labelConnex;
    private javax.swing.JLabel labelDBName;
    private javax.swing.JLabel labelPass;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
