/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnexBDPanel.java
 *
 * Created on 03-mai-2009, 0:09:36
 */

package View;

import java.util.Vector;

/**
 *
 * @author Cramike
 */
public class ConnexBDPanel extends javax.swing.JPanel {

    /** Creates new form ConnexBDPanel */
    public ConnexBDPanel() {
        initComponents();
    }

    public Vector<String> getID(){
        Vector<String> vec= new Vector<String>();
        if(!textBD.getText().isEmpty() && pass.getPassword().length>0)
        {
            vec.add(textBD.getText());
            vec.add(new String(pass.getPassword()));
        }
        return vec;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textBD = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Base de donnée :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 7, 4, 7);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Mot de passe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 7, 4, 7);
        add(jLabel2, gridBagConstraints);

        textBD.setText("festival");
        textBD.setMinimumSize(new java.awt.Dimension(110, 20));
        textBD.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 7, 4, 7);
        add(textBD, gridBagConstraints);

        pass.setMinimumSize(new java.awt.Dimension(110, 20));
        pass.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 7, 4, 7);
        add(pass, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField textBD;
    // End of variables declaration//GEN-END:variables

}
