/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * actionPanel.java
 *
 * Created on 27-mars-2009, 19:19:12
 */

package View.groupe;

/**
 *
 * @author Cramike
 */
public class actionPanel extends javax.swing.JPanel {

    /** Creates new form actionPanel */
    public actionPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butRetour = new javax.swing.JButton();
        butEnregistrer = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 46, 48)));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 4));

        butRetour.setText("Retour");
        butRetour.setToolTipText("Retour à la page d'accueil");
        add(butRetour);

        butEnregistrer.setText("Enregistrer le groupe");
        butEnregistrer.setToolTipText("Enregistrer le groupe dans la base de données");
        add(butEnregistrer);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butEnregistrer;
    private javax.swing.JButton butRetour;
    // End of variables declaration//GEN-END:variables

}
