/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultSearchMembrePanel.java
 *
 * Created on 01-mai-2009, 15:06:33
 */

package View.groupe;

import Business.AllResultMembreTableModel;
import Business.MembreGroupeAgrandi;
import Controller.Controller;
import Data.BDException;
import View.BarreInfo;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cramike
 */
public class ResultSearchMembrePanel extends javax.swing.JPanel {
    private AllResultMembreTableModel model;

    /** Creates new form ResultSearchMembrePanel */
    public ResultSearchMembrePanel() {
        model = new AllResultMembreTableModel();
        initComponents();
    }

    public void actualiser(CriteresRecherche c) {
        Vector <MembreGroupeAgrandi> vec;
        try {
            vec = Controller.getAllResultMembre(c);
            if(vec.isEmpty())
                System.out.println("Vide");
            model = new AllResultMembreTableModel(vec);
            table.setModel(model);
            table.validate();
        } catch (BDException ex) {
            System.out.println(ex.getMessage());
        }

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Résultats"));
        setMinimumSize(new java.awt.Dimension(470, 280));
        setPreferredSize(new java.awt.Dimension(470, 280));
        setLayout(new java.awt.GridLayout());

        table.setModel(model);
        scroll.setViewportView(table);

        add(scroll);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
