/*
 * SceneHoraireJPanel.java
 *
 * Created on 30 avril 2009, 13:56
 */

package View.scene;

/**
 *
 * @author  ig2scailletb
 */
public class SceneHoraireJPanel extends javax.swing.JPanel {

    /** Creates new form SceneHoraireJPanel */
    public SceneHoraireJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Horaire"));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
