/*
 * SceneInscriptionJPanel.java
 *
 * Created on 26 mars 2009, 14:27
 */
package View.scene;

import Controller.Controller;
import Data.BDException;
import Data.Scene;
import View.MainFrame;
import View.VerifyData;
import View.VerifyDataException;
import View.groupe.GroupeNotAcceptedException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author  ig2scailletb
 */
public class SceneInscriptionJPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private View.GestionFocusTextField gestionFocus = new View.GestionFocusTextField();
    private GestionAction gestionAction = new GestionAction();

    /** Creates new form SceneInscriptionJPanel */
    public SceneInscriptionJPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();

        //Gestion du focus
        this.textCapaciMax.addFocusListener(gestionFocus);
        this.textNbIng.addFocusListener(gestionFocus);
        this.textNom.addFocusListener(gestionFocus);
        this.textSuperficie.addFocusListener(gestionFocus);
        butSave.addActionListener(gestionAction);
        butReinit.addActionListener(gestionAction);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        combNum = new javax.swing.JComboBox();
        labelNumero = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        labelNom = new javax.swing.JLabel();
        labelCapMax = new javax.swing.JLabel();
        textCapaciMax = new javax.swing.JTextField();
        textSuperficie = new javax.swing.JTextField();
        labelSuperficie = new javax.swing.JLabel();
        labelNbIng = new javax.swing.JLabel();
        textNbIng = new javax.swing.JTextField();
        scrollTextCom = new javax.swing.JScrollPane();
        areaCommentaire = new javax.swing.JTextArea();
        labelCom = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        butReinit = new javax.swing.JButton();
        butSave = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Inscription Scène"));
        setLayout(new java.awt.GridBagLayout());

        combNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        combNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combNumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        add(combNum, gridBagConstraints);

        labelNumero.setText("Numéro : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(labelNumero, gridBagConstraints);

        textNom.setMinimumSize(new java.awt.Dimension(110, 20));
        textNom.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(textNom, gridBagConstraints);

        labelNom.setText("Nom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(labelNom, gridBagConstraints);

        labelCapMax.setText("Capacité maximum : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(labelCapMax, gridBagConstraints);

        textCapaciMax.setMinimumSize(new java.awt.Dimension(110, 20));
        textCapaciMax.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(textCapaciMax, gridBagConstraints);

        textSuperficie.setMinimumSize(new java.awt.Dimension(110, 20));
        textSuperficie.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(textSuperficie, gridBagConstraints);

        labelSuperficie.setText("Superificie : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(labelSuperficie, gridBagConstraints);

        labelNbIng.setText("Nombre d'ingénieurs requis : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(labelNbIng, gridBagConstraints);

        textNbIng.setMinimumSize(new java.awt.Dimension(110, 20));
        textNbIng.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(textNbIng, gridBagConstraints);

        areaCommentaire.setColumns(20);
        areaCommentaire.setRows(5);
        scrollTextCom.setViewportView(areaCommentaire);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(scrollTextCom, gridBagConstraints);

        labelCom.setText("Commentaire : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(labelCom, gridBagConstraints);

        butReinit.setText("Réinitialiser");
        butReinit.setMaximumSize(new java.awt.Dimension(140, 23));
        butReinit.setMinimumSize(new java.awt.Dimension(140, 23));
        butReinit.setPreferredSize(new java.awt.Dimension(140, 23));
        butReinit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReinitActionPerformed(evt);
            }
        });
        actionPanel.add(butReinit);

        butSave.setText("Sauver");
        butSave.setMaximumSize(new java.awt.Dimension(140, 23));
        butSave.setMinimumSize(new java.awt.Dimension(140, 23));
        butSave.setPreferredSize(new java.awt.Dimension(140, 23));
        actionPanel.add(butSave);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(actionPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verify() {
        if (this.textNom.getText().isEmpty() ||
                this.textCapaciMax.getText().isEmpty() ||
                this.textSuperficie.getText().isEmpty() ||
                this.textNbIng.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    private void reinit() {
        this.textNom.setText(null);
        this.textCapaciMax.setText(null);
        this.textSuperficie.setText(null);
        this.textNbIng.setText(null);
        this.areaCommentaire.setText(null);
    }

private void butReinitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReinitActionPerformed
}//GEN-LAST:event_butReinitActionPerformed

private void combNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combNumActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_combNumActionPerformed

    private class GestionAction implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == butSave) {
                if (verify()) {
                    int capacite, superficie, ingenieur;
                    try {
                        VerifyData v = new VerifyData();
                        capacite = v.getSQLInt(textCapaciMax.getText());
                        superficie = v.getSQLInt(textSuperficie.getText());
                        ingenieur = v.getSQLInt(textNbIng.getText());
                        Scene NewScene = new Scene(combNum.getSelectedIndex(), textNom.getText(), capacite, superficie, ingenieur, areaCommentaire.getText());
                        Controller.createScene(NewScene);
                    } catch (GroupeNotAcceptedException eg) {
                        mainFrame.getBarreInfo().setText(eg.toString());
                    } catch (VerifyDataException ed) {
                        mainFrame.getBarreInfo().setText(ed.toString());
                    }
                } else {
                    mainFrame.getBarreInfo().setText("Veuillez compléter tous les champs svp");
                }
            }
                else if (e.getSource() == butReinit) {
                    reinit();
                }         
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JTextArea areaCommentaire;
    private javax.swing.JButton butReinit;
    private javax.swing.JButton butSave;
    private javax.swing.JComboBox combNum;
    private javax.swing.JLabel labelCapMax;
    private javax.swing.JLabel labelCom;
    private javax.swing.JLabel labelNbIng;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelSuperficie;
    private javax.swing.JScrollPane scrollTextCom;
    private javax.swing.JTextField textCapaciMax;
    private javax.swing.JTextField textNbIng;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textSuperficie;
    // End of variables declaration//GEN-END:variables
}
